language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: gigstaff.surge.sh
  project: "./build/"
true:
  branch: master
notifications:
  email: false
env:
  global:
  - secure: Ox04M7P83N0YWMdWVLwjSrkvLWUml4lhs56HB/c84ltdpYiKkudyRCDYGnYfmnnszZnJATTzl43Oz/Xkam0uOldHp8BDJadJFb0aoo13pC4eDEjc2SdhpwnJVPa0xXinQbw3YbILLorjl1fSJzZS6kedUcCuJyD3u46b/JN3pGazA6/4NbIj72NpREqggLrZyIuvcBrRpWDY+RlV6P2MTfJNZSZn8Z/UAlwoxlZaOpgQpSm5JoKQpM7fEqIx9GT9Li5BoRxEprNFfd2Lz26Xo0I3v0rkhzhMjivW4xEh21iclmr8xKSJHq0Ijv6mJt89Aj3c/I6nSVwE4EQ9jqkQZ1Sjh40LO6djI+ViFGYwJVlQsdhhTiqvE/mAcW0xif0HmAsls5Kx/8cvbEwER81oFp7u+PAEJXKxNattHuIgFTNRTsx55aANvH8Nv8pCPyb/5HFJkiAceO5Z7JBlphs4V/hXXaN5T1RVpxK2agMkUi0O+sg85q1Rj/TdQrp0Oanfxq/IkUCbAJ6HA59TwvFJLsAEgRpJrChjohb/DhO/uWYw2+gJbERq5QfMrcSOrmIY82Y1gLPIhGAtkV5qDCVTxJ1Q/Nkr9KKcLD+WCF+wSYRvlgLY7zyy1YdcU09d9e32o0Le1n9OWnu0rzGpGhvbxw5mv+GKDLAI2wyOML4+c+s=
  - secure: CzaplTtR4Bh+glS3lQtdGqZ7d12uc50q9FrCeQJ6aZUkoRilWsq9fV+nxEne4IXaKGdF1r2Nf5p0SijCZgeV7QQND2ViKanf/TAlL9tgqp+zDrN51Zcuc2SxzY28znFiwMJnydcZSnS4tKf3wpXcvocHiiznhykC0FU9iuKeGvBWl6f7ZWufETeJ1UQSsFmyRtu+cRI8Lw4P22YxOSZgdOb9eGLc2yXuiZcvw2ZLzWb68TGV+aIATaGRa1gbJmaFPtqXdJyejU/IU3mNbwnnBwwlZH+FzcFxfikUMxruPbMkJGEQFwsA7s5ueKYovsdEuFdE2kKhUcNye+Aaq/eEmqn2cNLuRIIgQ0035dZp3CjgqFxJoYKZwW8XYWW3uscNPoaR+zpToCRGNVVIlqe9KDANgkgxFASvwCRj8ShOEOtKF39f2vrq3l+8O6WQTk50ddJP/07QnUITZ5kD4NUUkSVh7L+04S1myYWEZYt3avWqdxNNtXDOsChSUeZNVOfAHhmgQ5Xk8SB8LPu4EzGHwmL0ewISN678eUG5LGnuJ6HZ/Ytnqbc6H7e8Umn5L2hE3KFGKuyyLhUE/Ro2xcwzxmZd1xd++xj8ILyRiAsqZ+fcH9VDbTkpvDwbw5+TqneSV5IkpIBcSInDGnx45q/9TKNBg2NlzdmgZneeOvMkYZY=
  - secure: PWj7lOLOwsKtZEk1erssSVTkia1h07Wx6JkGltMGvwKokmhPluJZIMNWzbksHhA5RJ8qX+NDbjmmFgJuVoIFaGwvw2ZjnAkJsXd7Zezp98jC2QWb0JmI4eZ4Qj2VtLb9tU2YQ1mlLzYWmXIPuBeftPg3CfElGjDIPuU0iPe1k56eC5Hk2gYRJZuBJYPFftxiWUk9AutzUb7Gz5YVklR3Kr2tUZh4OdIeyGe0V4BFNg2x47GdzqLAie8X1Jou7pHml3S7WqEdPaIEL5Bl0pS8bJ8kDFgv1n2R3mLAlRjqzgdhBAlYgGXKNrT1afdJE4y9GfuIBh1/DqxlWP8aX07QmnvWghtc/iHiPT9aF7qLmt4JHm7OkmrsdiaaeAKJ60W5HFlmzJQg57fyBteEHyXYGhQIyVOCWXkA0nkhM7/lKOW20yVx0htkzfAo5EGiW9yubja+vWlVyeCClg647zw4fhBUQhZLnOsyYFCt4kGZqAQslmDQ792kW865U8quZzN2pA2qBgQJiLFon4O2+Znrl5QjFGhv3E3cC78qrV9+uP1TOzYoksj5RugKtqDoqxJKbdCOcG3423Db5owUr+OWXNujIZJiogw9O3DDh6lFpyjeoD7GK0cvn5N5LrHW6Z0oxtl2q0Rw8d0+BM6XNjdvvcgYOeMpIhjeG5wZMySr5Qs=
